// Sections
export const ADD_SECTION = 'ADD_SECTION';
export const UPDATE_SECTION = 'UPDATE_SECTION';
export const UPDATE_SECTION_ORDER = 'UPDATE_SECTION_ORDER';

// Settings
export const RESET_CONTENT = 'RESET_CONTENT';

// Breakout
export const ADDTO_BREAKOUT_HALLOFFAME = 'ADDTO_BREAKOUT_HALLOFFAME';